name: Publish to PyPI

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m build
          python -m twine check dist/*

      # Optional: print the METADATA to debug if this ever fails again
      - name: Inspect wheel METADATA (debug)
        if: failure()
        run: |
          python - <<'PY'
          import zipfile, glob
          wheel = sorted(glob.glob("dist/*.whl"))[-1]
          with zipfile.ZipFile(wheel) as zf:
              meta = [n for n in zf.namelist() if n.endswith(".dist-info/METADATA")][0]
              print("=== METADATA from", wheel, "===\n")
              print(zf.read(meta).decode("utf-8"))
          PY

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
